name: "Send E-Mail (SMTP)"
description: "Sending Email via SMTP"
branding:
  icon: "mail"
  color: "orange"
inputs:
  smtp-server:
    description: "The smtp server to use"
    required: false
  smtp-port:
    description: "The smtp port to use"
    required: false
    default: "465"
  smtp-secure:
    description: "If the smtp server uses ssl"
    required: false
    default: "true"
  from-email:
    description: "The sender of the mail"
    required: false
  to-email:
    description: "The recipients of the mail seperated by comma"
    required: false
  username:
    description: "The username of the mail account"
    required: false
  password:
    description: "The password of the mail account"
    required: false
  subject:
    description: "The subject of the mail"
    required: false
  body:
    description: "The body of the mail"
  html:
    description: "HTML Content of the mail"

runs:
  using: node20
  main: "dist/index.js"
